### ISSUE TITLE
dev.Dockerfile bazel test failure

### ISSUE THREAD

**Issue by wangshangsam** [tensorflow/lingvo#220]
Hi,

I tried to follow the instruction in https://github.com/tensorflow/lingvo/blob/master/docker/dev.dockerfile#L3 to L10. However, bazel reports a compile error:

```
root@581ea70a3d6f:/tmp/lingvo# bazel test -c opt --test_output=streamed //lingvo:trainer_test //lingvo:models_test
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
WARNING: Streamed test output requested. All tests will be run locally, without sharding, one at a time
DEBUG: Rule 'subpar' indicated that a canonical reproducible form can be obtained by modifying arguments commit = "35bb9f0092f71ea56b742a520602da9b3638a24f", shallow_since = "1557863961 -0400" and dropping ["tag"]
DEBUG: Call stack for the definition of repository 'subpar' which is a git_repository (rule definition at /root/.cache/bazel/_bazel_root/17eb95f0bc03547f4f1319e61997e114/external/bazel_tools/tools/build_defs/repo/git.bzl:181:18):
 - /tmp/lingvo/WORKSPACE:11:1
INFO: Analyzed 2 targets (50 packages loaded, 5989 targets configured).
INFO: Found 2 test targets...
ERROR: /tmp/lingvo/lingvo/core/ops/BUILD:109:1: C++ compilation of rule '//lingvo/core/ops:record' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 71 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from ./lingvo/core/ops/record_yielder.h:27:0,
                 from lingvo/core/ops/record_yielder.cc:16:
./lingvo/core/ops/mutex.h:61:13: error: expected ';' at end of member declaration
   void Lock() EXCLUSIVE_LOCK_FUNCTION() { nsync_mu_lock(&mu_); }
             ^
./lingvo/core/ops/mutex.h:61:39: error: ISO C++ forbids declaration of 'EXCLUSIVE_LOCK_FUNCTION' with no type [-fpermissive]
   void Lock() EXCLUSIVE_LOCK_FUNCTION() { nsync_mu_lock(&mu_); }
                                       ^
./lingvo/core/ops/mutex.h:63:15: error: expected ';' at end of member declaration
   void Unlock() UNLOCK_FUNCTION() { nsync_mu_unlock(&mu_); }
               ^
./lingvo/core/ops/mutex.h:63:33: error: ISO C++ forbids declaration of 'UNLOCK_FUNCTION' with no type [-fpermissive]
   void Unlock() UNLOCK_FUNCTION() { nsync_mu_unlock(&mu_); }
                                 ^
./lingvo/core/ops/mutex.h: In member function 'int tensorflow::lingvo::Mutex::EXCLUSIVE_LOCK_FUNCTION()':
./lingvo/core/ops/mutex.h:61:64: warning: no return statement in function returning non-void [-Wreturn-type]
   void Lock() EXCLUSIVE_LOCK_FUNCTION() { nsync_mu_lock(&mu_); }
                                                                ^
./lingvo/core/ops/mutex.h: In member function 'int tensorflow::lingvo::Mutex::UNLOCK_FUNCTION()':
./lingvo/core/ops/mutex.h:63:60: warning: no return statement in function returning non-void [-Wreturn-type]
   void Unlock() UNLOCK_FUNCTION() { nsync_mu_unlock(&mu_); }
                                                            ^
./lingvo/core/ops/mutex.h: At global scope:
./lingvo/core/ops/mutex.h:76:23: error: variable 'tensorflow::lingvo::SCOPED_LOCKABLE tensorflow::lingvo::MutexLock' has initializer but incomplete type
 class SCOPED_LOCKABLE MutexLock {
                       ^~~~~~~~~
./lingvo/core/ops/mutex.h:77:2: error: expected primary-expression before 'public'
  public:
  ^~~~~~
./lingvo/core/ops/mutex.h:77:2: error: expected '}' before 'public'
./lingvo/core/ops/mutex.h:77:2: error: expected ',' or ';' before 'public'
./lingvo/core/ops/mutex.h:82:13: error: expected class-name before '(' token
   ~MutexLock() UNLOCK_FUNCTION() { mu_->Unlock(); }
             ^
./lingvo/core/ops/mutex.h:84:2: error: expected unqualified-id before 'private'
  private:
  ^~~~~~~
In file included from ./lingvo/core/ops/mutex.h:23:0,
                 from ./lingvo/core/ops/record_yielder.h:27,
                 from lingvo/core/ops/record_yielder.cc:16:
./lingvo/core/ops/mutex.h:87:31: error: 'MutexLock' does not name a type; did you mean 'mutex_lock'?
   TF_DISALLOW_COPY_AND_ASSIGN(MutexLock);
                               ^
./lingvo/core/ops/mutex.h:87:3: error: expected constructor, destructor, or type conversion before '=' token
   TF_DISALLOW_COPY_AND_ASSIGN(MutexLock);
   ^
./lingvo/core/ops/mutex.h:87:31: error: 'MutexLock' does not name a type; did you mean 'mutex_lock'?
   TF_DISALLOW_COPY_AND_ASSIGN(MutexLock);
                               ^
./lingvo/core/ops/mutex.h:87:3: error: 'void tensorflow::lingvo::operator=(const int&)' must be a nonstatic member function
   TF_DISALLOW_COPY_AND_ASSIGN(MutexLock);
   ^
In file included from ./lingvo/core/ops/record_yielder.h:27:0,
                 from lingvo/core/ops/record_yielder.cc:16:
./lingvo/core/ops/mutex.h:111:1: error: expected declaration before '}' token
 }  // namespace tensorflow
 ^
INFO: Elapsed time: 19.853s, Critical Path: 5.62s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
//lingvo:trainer_test                                                 NO STATUS

FAILED: Build did NOT complete successfully
```

Does anyone have insight on how to resolve this?

Thanks!

**Comment by jonathanasdf** [comment]
Hi, Lingvo doesn't work with the latest tf 2.2.0. You need to change the dockerfile to install 2.1.0 for now. See https://github.com/tensorflow/lingvo/pull/219 for example.

**Comment by jonathanasdf** [comment]
The latest version should now work with tf 2.2.0.
